import "./globals.css";
import { Inter } from "next/font/google";
import GlobalHeader from "./components/globalHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

if (!global.CmsClient) {
    (async () => {
        global.CmsClient = (
            await import("@/cmsTypescriptClient/cmsClient")
        ).CmsClient;
    })();
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                {/* @ts-expect-error Async Server Component */}
                <GlobalHeader></GlobalHeader>
                {children}
            </body>
        </html>
    );
}
