/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ImageComponent,
    instanceOfImageComponent,
    ImageComponentFromJSON,
    ImageComponentFromJSONTyped,
    ImageComponentToJSON,
} from './ImageComponent';
import {
    TextComponent,
    instanceOfTextComponent,
    TextComponentFromJSON,
    TextComponentFromJSONTyped,
    TextComponentToJSON,
} from './TextComponent';

/**
 * @type GridColumnComponent
 * 
 * @export
 */
export type GridColumnComponent = ImageComponent | TextComponent;

export function GridColumnComponentFromJSON(json: any): GridColumnComponent {
    return GridColumnComponentFromJSONTyped(json, false);
}

export function GridColumnComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): GridColumnComponent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ImageComponentFromJSONTyped(json, true), ...TextComponentFromJSONTyped(json, true) };
}

export function GridColumnComponentToJSON(value?: GridColumnComponent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfImageComponent(value)) {
        return ImageComponentToJSON(value as ImageComponent);
    }
    if (instanceOfTextComponent(value)) {
        return TextComponentToJSON(value as TextComponent);
    }

    return {};
}

