/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Component } from './Component';
import {
    ComponentFromJSON,
    ComponentFromJSONTyped,
    ComponentToJSON,
} from './Component';

/**
 * 
 * @export
 * @interface ImageComponent
 */
export interface ImageComponent extends Component {
    /**
     * 
     * @type {string}
     * @memberof ImageComponent
     */
    imageUrl?: string | null;
}

/**
 * Check if a given object implements the ImageComponent interface.
 */
export function instanceOfImageComponent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ImageComponentFromJSON(json: any): ImageComponent {
    return ImageComponentFromJSONTyped(json, false);
}

export function ImageComponentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageComponent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ComponentFromJSONTyped(json, ignoreDiscriminator),
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
    };
}

export function ImageComponentToJSON(value?: ImageComponent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ComponentToJSON(value),
        'imageUrl': value.imageUrl,
    };
}

