/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductCategory
 */
export interface ProductCategory {
    /**
     * 
     * @type {number}
     * @memberof ProductCategory
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductCategory
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductCategory
     */
    description?: string | null;
    /**
     * 
     * @type {Array<ProductCategory>}
     * @memberof ProductCategory
     */
    subcategories?: Array<ProductCategory> | null;
}

/**
 * Check if a given object implements the ProductCategory interface.
 */
export function instanceOfProductCategory(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductCategoryFromJSON(json: any): ProductCategory {
    return ProductCategoryFromJSONTyped(json, false);
}

export function ProductCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'subcategories': !exists(json, 'subcategories') ? undefined : (json['subcategories'] === null ? null : (json['subcategories'] as Array<any>).map(ProductCategoryFromJSON)),
    };
}

export function ProductCategoryToJSON(value?: ProductCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'subcategories': value.subcategories === undefined ? undefined : (value.subcategories === null ? null : (value.subcategories as Array<any>).map(ProductCategoryToJSON)),
    };
}

